name: CI

on: [push]

jobs:
  build:

    runs-on: centos:7

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        yum install ansible
        ls -la
        cd tests && ansible-playbook -i localhost test.yml -vv
